//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExandasOracle.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExandasOracle.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;About....
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the following record :.
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking the connection.
        /// </summary>
        internal static string CheckingTheConnection {
            get {
                return ResourceManager.GetString("CheckingTheConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à check constraints.
        /// </summary>
        internal static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cluster column mappings.
        /// </summary>
        internal static string ClusterColumnMappings {
            get {
                return ResourceManager.GetString("ClusterColumnMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cluster columns.
        /// </summary>
        internal static string ClusterColumns {
            get {
                return ResourceManager.GetString("ClusterColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cluster indexes.
        /// </summary>
        internal static string ClusterIndexes {
            get {
                return ResourceManager.GetString("ClusterIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à clusters.
        /// </summary>
        internal static string Clusters {
            get {
                return ResourceManager.GetString("Clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à column comments.
        /// </summary>
        internal static string ColumnComments {
            get {
                return ResourceManager.GetString("ColumnComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        internal static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compaction completed.
        /// </summary>
        internal static string CompactionCompleted {
            get {
                return ResourceManager.GetString("CompactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact the local database.
        /// </summary>
        internal static string CompactLocalDatabase {
            get {
                return ResourceManager.GetString("CompactLocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Compact the local database.
        /// </summary>
        internal static string CompactLocalDatabaseMenu {
            get {
                return ResourceManager.GetString("CompactLocalDatabaseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison report.
        /// </summary>
        internal static string ComparisonReport {
            get {
                return ResourceManager.GetString("ComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set detail.
        /// </summary>
        internal static string ComparisonSetDetail {
            get {
                return ResourceManager.GetString("ComparisonSetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set ID.
        /// </summary>
        internal static string ComparisonSetID {
            get {
                return ResourceManager.GetString("ComparisonSetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of comparison sets.
        /// </summary>
        internal static string ComparisonSetList {
            get {
                return ResourceManager.GetString("ComparisonSetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set name.
        /// </summary>
        internal static string ComparisonSetName {
            get {
                return ResourceManager.GetString("ComparisonSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison sets.
        /// </summary>
        internal static string ComparisonSets {
            get {
                return ResourceManager.GetString("ComparisonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection ID.
        /// </summary>
        internal static string ConnectionID {
            get {
                return ResourceManager.GetString("ConnectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection name.
        /// </summary>
        internal static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection name required.
        /// </summary>
        internal static string ConnectionNameRequired {
            get {
                return ResourceManager.GetString("ConnectionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à constraint columns.
        /// </summary>
        internal static string ConstraintColumns {
            get {
                return ResourceManager.GetString("ConstraintColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à constraints.
        /// </summary>
        internal static string Constraints {
            get {
                return ResourceManager.GetString("Constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DBA views.
        /// </summary>
        internal static string DBAViews {
            get {
                return ResourceManager.GetString("DBAViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete record ?.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delta of {0}.
        /// </summary>
        internal static string DeltaOf {
            get {
                return ResourceManager.GetString("DeltaOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you confirm the generation of the comparison report ?.
        /// </summary>
        internal static string DoYouConfirmGeneration {
            get {
                return ResourceManager.GetString("DoYouConfirmGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ExandasOracle Error.
        /// </summary>
        internal static string ExandasOracleError {
            get {
                return ResourceManager.GetString("ExandasOracleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export in Excel format.
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File size : .
        /// </summary>
        internal static string FileSizeColon {
            get {
                return ResourceManager.GetString("FileSizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à foreign keys.
        /// </summary>
        internal static string ForeignKeys {
            get {
                return ResourceManager.GetString("ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form data validation error..
        /// </summary>
        internal static string FormError {
            get {
                return ResourceManager.GetString("FormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à for Oracle®.
        /// </summary>
        internal static string ForOracle {
            get {
                return ResourceManager.GetString("ForOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate the comparison report.
        /// </summary>
        internal static string GenerateComparisonReport {
            get {
                return ResourceManager.GetString("GenerateComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison report generation in progress....
        /// </summary>
        internal static string GenerationInProgress {
            get {
                return ResourceManager.GetString("GenerationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host name.
        /// </summary>
        internal static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname required.
        /// </summary>
        internal static string HostnameRequired {
            get {
                return ResourceManager.GetString("HostnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à identity columns.
        /// </summary>
        internal static string IdentityColumns {
            get {
                return ResourceManager.GetString("IdentityColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à index columns.
        /// </summary>
        internal static string IndexColumns {
            get {
                return ResourceManager.GetString("IndexColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à index expressions.
        /// </summary>
        internal static string IndexExpressions {
            get {
                return ResourceManager.GetString("IndexExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à index partitions.
        /// </summary>
        internal static string IndexPartitions {
            get {
                return ResourceManager.GetString("IndexPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à index subpartitions.
        /// </summary>
        internal static string IndexSubpartitions {
            get {
                return ResourceManager.GetString("IndexSubpartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last comparison report.
        /// </summary>
        internal static string LastComparisonReport {
            get {
                return ResourceManager.GetString("LastComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last report time.
        /// </summary>
        internal static string LastReportTime {
            get {
                return ResourceManager.GetString("LastReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch of the comparison report ?.
        /// </summary>
        internal static string LaunchComparisonReport {
            get {
                return ResourceManager.GetString("LaunchComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading {1} {0}.
        /// </summary>
        internal static string LoadingObjects {
            get {
                return ResourceManager.GetString("LoadingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database.
        /// </summary>
        internal static string LocalDatabase {
            get {
                return ResourceManager.GetString("LocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database backup.
        /// </summary>
        internal static string LocalDatabaseBackup {
            get {
                return ResourceManager.GetString("LocalDatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database :.
        /// </summary>
        internal static string LocalDatabaseColon {
            get {
                return ResourceManager.GetString("LocalDatabaseColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Local database size.
        /// </summary>
        internal static string LocalDatabaseSize {
            get {
                return ResourceManager.GetString("LocalDatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à materialized views.
        /// </summary>
        internal static string MaterializedViews {
            get {
                return ResourceManager.GetString("MaterializedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;Not specified&gt;.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object in source absent in target.
        /// </summary>
        internal static string ObjectInSource {
            get {
                return ResourceManager.GetString("ObjectInSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object in target absent in source.
        /// </summary>
        internal static string ObjectInTarget {
            get {
                return ResourceManager.GetString("ObjectInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à object privileges.
        /// </summary>
        internal static string ObjectPrivileges {
            get {
                return ResourceManager.GetString("ObjectPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation canceled..
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à partitioned indexes.
        /// </summary>
        internal static string PartitionedIndexes {
            get {
                return ResourceManager.GetString("PartitionedIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à partitioned tables.
        /// </summary>
        internal static string PartitionedTables {
            get {
                return ResourceManager.GetString("PartitionedTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port required.
        /// </summary>
        internal static string PortRequired {
            get {
                return ResourceManager.GetString("PortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à primary keys.
        /// </summary>
        internal static string PrimaryKeys {
            get {
                return ResourceManager.GetString("PrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property difference.
        /// </summary>
        internal static string PropertyDifference {
            get {
                return ResourceManager.GetString("PropertyDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purge comparison reports.
        /// </summary>
        internal static string PurgeComparisonReports {
            get {
                return ResourceManager.GetString("PurgeComparisonReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purging comparison reports.
        /// </summary>
        internal static string PurgingComparisonReports {
            get {
                return ResourceManager.GetString("PurgingComparisonReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purging metadata tables.
        /// </summary>
        internal static string PurgingMetadata {
            get {
                return ResourceManager.GetString("PurgingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restoring the local database.
        /// </summary>
        internal static string RestoringLocalDatabase {
            get {
                return ResourceManager.GetString("RestoringLocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sequences.
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server connection detail.
        /// </summary>
        internal static string ServerConnectionDetail {
            get {
                return ResourceManager.GetString("ServerConnectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server connections.
        /// </summary>
        internal static string ServerConnections {
            get {
                return ResourceManager.GetString("ServerConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of server connections.
        /// </summary>
        internal static string ServerConnectionsList {
            get {
                return ResourceManager.GetString("ServerConnectionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SID or service name required.
        /// </summary>
        internal static string SIDOrServiceNameRequired {
            get {
                return ResourceManager.GetString("SIDOrServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source connection.
        /// </summary>
        internal static string SourceConnection {
            get {
                return ResourceManager.GetString("SourceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sources.
        /// </summary>
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source schema.
        /// </summary>
        internal static string SourceSchema {
            get {
                return ResourceManager.GetString("SourceSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source server connection.
        /// </summary>
        internal static string SourceServerConnection {
            get {
                return ResourceManager.GetString("SourceServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful connection.
        /// </summary>
        internal static string SuccessfulConnection {
            get {
                return ResourceManager.GetString("SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à synonyms.
        /// </summary>
        internal static string Synonyms {
            get {
                return ResourceManager.GetString("Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à table columns.
        /// </summary>
        internal static string TableColumns {
            get {
                return ResourceManager.GetString("TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à table indexes.
        /// </summary>
        internal static string TableIndexes {
            get {
                return ResourceManager.GetString("TableIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à table partitions.
        /// </summary>
        internal static string TablePartitions {
            get {
                return ResourceManager.GetString("TablePartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à table subpartitions.
        /// </summary>
        internal static string TableSubpartitions {
            get {
                return ResourceManager.GetString("TableSubpartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target connection.
        /// </summary>
        internal static string TargetConnection {
            get {
                return ResourceManager.GetString("TargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target schema.
        /// </summary>
        internal static string TargetSchema {
            get {
                return ResourceManager.GetString("TargetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target server connection.
        /// </summary>
        internal static string TargetServerConnection {
            get {
                return ResourceManager.GetString("TargetServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à triggers.
        /// </summary>
        internal static string Triggers {
            get {
                return ResourceManager.GetString("Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TRUNCATED.
        /// </summary>
        internal static string Truncated {
            get {
                return ResourceManager.GetString("Truncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to access DBA views.
        /// </summary>
        internal static string UnableToAccess {
            get {
                return ResourceManager.GetString("UnableToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à uniques.
        /// </summary>
        internal static string Uniques {
            get {
                return ResourceManager.GetString("Uniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name required.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à view columns.
        /// </summary>
        internal static string ViewColumns {
            get {
                return ResourceManager.GetString("ViewColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View the comparison report.
        /// </summary>
        internal static string ViewComparisonReport {
            get {
                return ResourceManager.GetString("ViewComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
